# Use the official Golang image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the necessary files into the container
COPY go.mod go.sum ./
COPY cmd/api/main.go ./cmd/api/
COPY internal internal/

# Build the Go app
RUN go mod download
RUN go build -o api-service ./cmd/api/main.go

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./api-service"]
