# Use the official Golang image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the necessary files into the container
COPY . .

# Download and install dependencies
RUN go mod download

# Build the Go app
RUN go build -o auth-service cmd/auth/main.go

# Expose port 50052 to the outside world
EXPOSE 50052

# Command to run the executable
CMD ["./auth-service"]
