# Use the official Golang image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the necessary files into the container
COPY . .

# Download and install dependencies
RUN go mod download

# Build the Go app
RUN go build -o user-service cmd/user/main.go

# Expose port 50051 to the outside world
EXPOSE 50051

# Command to run the executable
CMD ["./user-service"]
